# Generated by Django 6.1 on 2026-09-08 17:30

import core.validators.cpf
import core.validators.dn
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('nome_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Social')),
                ('mae', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Mãe')),
                ('pai', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Pai')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[core.validators.cpf.valida_cpf], verbose_name='CPF')),
                ('dn', models.DateField(validators=[core.validators.dn.valida_dn], verbose_name='Data de Nascimento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('cadastrante', models.CharField(max_length=75, verbose_name='Responsável pelo cadastro')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
    ]
