# Generated by Django 6.1 on 2026-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pessoa_data_cadastro_pessoa_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro'),
        ),
    ]
