# Generated by Django 6.1 on 2026-09-14 17:34

import core.models.pessoa
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pessoa_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone', models.CharField(max_length=15, verbose_name='Número do telefone')),
                ('nome_contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do contato')),
                ('vinculo', models.CharField(blank=True, choices=[('proprio', 'Próprio'), ('pai', 'Pai'), ('mae', 'Mãe'), ('filho', 'Filho'), ('conjuge', 'Cônjuge')], default='proprio', max_length=15, null=True, verbose_name='Vinculo')),
                ('wa', models.BooleanField(default=True, verbose_name='Whatsapp')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa', verbose_name=core.models.pessoa.Pessoa)),
            ],
        ),
    ]
