# Generated by Django 6.1 on 2026-09-14 18:54

import core.validators.fone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='id',
        ),
        migrations.AlterField(
            model_name='telefone',
            name='fone',
            field=models.CharField(help_text='(DDD)123456789', max_length=15, primary_key=True, serialize=False, validators=[core.validators.fone.valida_fone], verbose_name='Número do telefone'),
        ),
    ]
