# Generated by Django 6.1 on 2026-08-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regional', '0002_distrito_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('cnes', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='CNES')),
                ('nome', models.CharField(max_length=75, verbose_name='Nome')),
                ('nome_oficial', models.CharField(max_length=75, verbose_name='Nome Oficial')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Nome amigável para url', unique=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubss', to='regional.distrito')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
