# Generated by Django 6.1 on 2026-08-28 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubs',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
