# Generated by Django 6.1 on 2026-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencial', '0002_ubs_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubs',
            options={'ordering': ['nome'], 'verbose_name': 'Unidade Básica de Saúde', 'verbose_name_plural': 'Unidades Básicas de Saúde'},
        ),
        migrations.AlterField(
            model_name='ubs',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
