# Generated by Django 6.1 on 2026-09-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencial', '0003_alter_ubs_options_alter_ubs_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('cnes', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='CNES')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Nome amigável para url', max_length=120, unique=True)),
                ('vinculo', models.CharField(max_length=120, verbose_name='Vínculo')),
                ('sigla', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ubs',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ubs',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='Nome amigável para url', max_length=120, unique=True),
        ),
    ]
