# Generated by Django 6.1 on 2026-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencial', '0005_remove_especialidade_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro'),
        ),
        migrations.AlterField(
            model_name='ubs',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro'),
        ),
    ]
