# Generated by Django 5.1.6 on 2026-09-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencial', '0007_especialidade_data_cadastro_ubs_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidade',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='ubs',
            name='data_cadastro',
        ),
    ]
