# Generated by Django 6.1 on 2026-09-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencial', '0008_remove_especialidade_data_cadastro_and_more'),
        ('regional', '0006_remove_distrito_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubs',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubss', to='regional.distrito', verbose_name='Distrito'),
        ),
        migrations.CreateModel(
            name='Ceco',
            fields=[
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro')),
                ('cadastrante', models.CharField(default='Desenvolvimento', max_length=150, verbose_name='Cadastrante')),
                ('cnes', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='CNES')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Nome amigável para url', max_length=120, unique=True)),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cecos', to='regional.distrito', verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Centro de Convivência e Oficina',
                'verbose_name_plural': 'Centros de Convivência e Oficinas',
            },
        ),
    ]
