# Generated by Django 6.1 on 2026-09-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencial', '0009_alter_ubs_distrito_ceco'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCeco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro')),
                ('cadastrante', models.CharField(default='Desenvolvimento', max_length=150, verbose_name='Cadastrante')),
                ('dia', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (0, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_abre', models.TimeField(verbose_name='Horario de Abertura')),
                ('hora_fecha', models.TimeField(verbose_name='Horário de Fechamento')),
                ('ceco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='assistencial.ceco', verbose_name='Horários Cecos')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro')),
                ('cadastrante', models.CharField(default='Desenvolvimento', max_length=150, verbose_name='Cadastrante')),
                ('dia', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (0, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_abre', models.TimeField(verbose_name='Horario de Abertura')),
                ('hora_fecha', models.TimeField(verbose_name='Horário de Fechamento')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='assistencial.especialidade', verbose_name='Horários Especialide')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioUbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro')),
                ('cadastrante', models.CharField(default='Desenvolvimento', max_length=150, verbose_name='Cadastrante')),
                ('dia', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (0, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_abre', models.TimeField(verbose_name='Horario de Abertura')),
                ('hora_fecha', models.TimeField(verbose_name='Horário de Fechamento')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='assistencial.ubs', verbose_name='Unidade Básica de Saúde')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'abstract': False,
            },
        ),
    ]
