# Generated by Django 6.1 on 2026-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencial', '0010_horarioceco_horarioespecialidade_horarioubs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioceco',
            options={},
        ),
        migrations.AlterModelOptions(
            name='horarioespecialidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='horarioubs',
            options={},
        ),
        migrations.AddConstraint(
            model_name='horarioceco',
            constraint=models.UniqueConstraint(fields=('ceco', 'dia'), name='unique_ceco_dia', violation_error_message='Já existe horario cadastrado para este dia no referido ceco'),
        ),
        migrations.AddConstraint(
            model_name='horarioespecialidade',
            constraint=models.UniqueConstraint(fields=('especialidade', 'dia'), name='unique_especialidade_dia', violation_error_message='Já existe horario cadastrado para este dia na referida especialidade'),
        ),
        migrations.AddConstraint(
            model_name='horarioubs',
            constraint=models.UniqueConstraint(fields=('ubs', 'dia'), name='unique_ubs_dia', violation_error_message='Já existe horario cadastrado para este dia na referida UBS'),
        ),
    ]
