# Generated by Django 5.1.6 on 2026-09-11 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_pessoa_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupacaoCBO',
            fields=[
                ('cbo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('profissao', models.CharField(max_length=150, verbose_name='Profissão')),
                ('conselho', models.CharField(blank=True, choices=[('CRM', 'Conselho Regional de Medicina'), ('COREN', 'Conselho Regional de Enfermagem'), ('CRP', 'Conselho Regional de Psicologia'), ('CRO', 'Conselho Regional de Odontologia'), ('CRN', 'Conselho Regional de Nutrição'), ('CREFITO', 'Conselho Reg. de Fisioterapia e Terapia Ocupacional'), ('CRF', 'Conselho Regional de Farmácia'), ('CRBM', 'Conselho Regional de Biomedicina'), ('CRBio', 'Conselho Regional de Biologia'), ('CREF', 'Conselho Regional de Educação Física'), ('CRESS', 'Conselho Regional de Serviço Social'), ('CRMV', 'Conselho Regional de Medicina Veterinária'), ('CREFONO', 'Conselho Regional de Fonoaudiologia')], max_length=10, null=True, verbose_name='Conselho')),
            ],
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro')),
                ('cadastrante', models.CharField(default='Desenvolvimento', max_length=150, verbose_name='Cadastrante')),
                ('matricula', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('data_contratacao', models.DateField(verbose_name='Data da Contratação')),
                ('num_conselho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Conselho')),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='profissionais.ocupacaocbo', verbose_name='Ocupação (CBO)')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profissional', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['pessoa__nome'],
            },
        ),
    ]
