# Generated by Django 6.1 on 2026-09-16 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocupacaocbo',
            options={'ordering': ['profissao'], 'verbose_name': 'Ocupação CBO', 'verbose_name_plural': 'Ocupações CBOs'},
        ),
        migrations.AddField(
            model_name='ocupacaocbo',
            name='cadastrante',
            field=models.CharField(default='Desenvolvimento', max_length=150, verbose_name='Cadastrante'),
        ),
        migrations.AddField(
            model_name='ocupacaocbo',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datetime cadastro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocupacaocbo',
            name='cbo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='CBO'),
        ),
        migrations.AlterField(
            model_name='ocupacaocbo',
            name='profissao',
            field=models.CharField(choices=[('Agente Administrativo', 'Agente Administrativo'), ('Angiologista', 'Angiologista'), ('Assistente Social', 'Assistente Social'), ('Biomédico', 'Biomédico'), ('Biólogo', 'Biólogo'), ('Cardiologista', 'Cardiologista'), ('Cirurgião Dentista', 'Cirurgião Dentista'), ('Clínico Geral', 'Clínico Geral'), ('Coloproctologista', 'Coloproctologista'), ('Educador Física', 'Educador Física'), ('Endocrinologista', 'Endocrinologista'), ('Enfermeiro', 'Enfermeiro'), ('Farmacêutico', 'Farmacêutico'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Fonoaudiólogo', 'Fonoaudiólogo'), ('Ginecologista/Obstetra', 'Ginecologista/Obstetra'), ('Hematologista', 'Hematologista'), ('Mastologista', 'Mastologista'), ('Nefrologista', 'Nefrologista'), ('Neurocirurgião', 'Neurocirurgião'), ('Neurologista', 'Neurologista'), ('Nutricionista', 'Nutricionista'), ('Ortopedista/Traumatologista', 'Ortopedista/Traumatologista'), ('Pediatra', 'Pediatra'), ('Pneumologista', 'Pneumologista'), ('Psicólogo', 'Psicólogo'), ('Psiquiatra', 'Psiquiatra'), ('Reumatologista', 'Reumatologista'), ('Tec Enfermagem', 'Tec Enfermagem'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional'), ('Urologista', 'Urologista'), ('Veterinário', 'Veterinário')], max_length=150, verbose_name='Profissão'),
        ),
    ]
