# Generated by Django 6.1 on 2026-09-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_telefone_id_alter_telefone_fone'),
        ('profissionais', '0002_alter_ocupacaocbo_options_ocupacaocbo_cadastrante_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profissionais',
            new_name='Profissional',
        ),
    ]
