# Generated by Django 6.1 on 2026-08-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('cnes', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='CNES')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Nome amigável para url', unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
