# Generated by Django 6.1 on 2026-08-24 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Cadastro'),
            preserve_default=False,
        ),
    ]
