# Generated by Django 5.1.6 on 2026-09-09 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0002_distrito_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='distrito',
            name='cadastrante',
            field=models.CharField(default='Desenvolvimento', max_length=150, verbose_name='Cadastrante'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime cadastro'),
        ),
    ]
