# Generated by Django 6.1 on 2026-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0003_remove_distrito_data_cadastro_distrito_cadastrante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro'),
        ),
    ]
