# Generated by Django 6.1 on 2026-09-22 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0004_alter_distrito_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
