# Generated by Django 5.1.6 on 2026-09-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0005_distrito_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='data_cadastro',
        ),
    ]
