# Generated by Django 5.1.6 on 2026-09-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0006_remove_distrito_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDistrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime cadastro')),
                ('cadastrante', models.CharField(default='Desenvolvimento', max_length=150, verbose_name='Cadastrante')),
                ('dia', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (0, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_abre', models.TimeField(verbose_name='Horario de Abertura')),
                ('hora_fecha', models.TimeField(verbose_name='Horário de Fechamento')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional.distrito', verbose_name='Distrito')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('distrito', 'dia'), name='unique_distrito_dia')],
            },
        ),
    ]
