# Generated by Django 6.1 on 2026-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0007_horariodistrito'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='horariodistrito',
            name='unique_distrito_dia',
            constraint=models.UniqueConstraint(fields=('distrito', 'dia'), name='unique_distrito_dia', violation_error_message='Já existe horario cadastrado para este dia no referido distrito'),
        ),
    ]
