# Generated by Django 6.1 on 2026-09-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0008_alter_horariodistrito_unique_distrito_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodistrito',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='regional.distrito', verbose_name='Distrito'),
        ),
    ]
